setwd("~/Documents/GitHub/Data Science Specialization/3) Getting and Cleaning Data/Course Project")

# Read the list of features (column names in the dataset)
features <- read.table("UCI HAR Dataset/features.txt",col.names=c("Index","Feature"))

# Find the column names that contain 'mean()' or 'std()' using regular
# expressions. It took some time to figure out that I need to escape
# the backslashes too.
colKeep <- grep("\\<mean()\\>|\\<std()\\>",features$Feature)

# Clean up the feature names to make them more readable
extractedFeatures <- as.character(features$Feature[colKeep])
extractedFeatures <- gsub("BodyBody","body.",extractedFeatures)
extractedFeatures <- gsub("Body","body.",extractedFeatures)
extractedFeatures <- gsub("-","",extractedFeatures)
extractedFeatures <- gsub("Acc","accelerometer.",extractedFeatures)
extractedFeatures <- gsub("Gyro","gyroscope.",extractedFeatures)
extractedFeatures <- gsub("mean[(][)]","mean.",extractedFeatures)
extractedFeatures <- gsub("std[(][)]","standard.deviation.",extractedFeatures)
extractedFeatures <- gsub("Jerk","jerk.",extractedFeatures)
extractedFeatures <- gsub("Gravity","gravity.",extractedFeatures)
extractedFeatures <- gsub("^t","time.",extractedFeatures)
extractedFeatures <- gsub("^f","frequency.",extractedFeatures)
extractedFeatures <- gsub("Mag","magnitude.",extractedFeatures)
extractedFeatures <- gsub("\\.$","",extractedFeatures)
extractedFeatures <- tolower(extractedFeatures)
extractedFeatures

# read the feature data for the training and test sets
train <- read.table("UCI HAR Dataset/train/X_train.txt")
test <- read.table("UCI HAR Dataset/test/X_test.txt")

# Keep only the columns with mean() or std()
train <- train[,colKeep]
test <- test[,colKeep]

# read the labels for the training and test sets
trainlabels <- read.table("UCI HAR Dataset/train/Y_train.txt")
testlabels <- read.table("UCI HAR Dataset/test/Y_test.txt")
train$activity <- trainlabels$V1
test$activity <- testlabels$V1

# Read the subject each observation was generated by, and add to the datasets
subjects_train <- read.table("UCI HAR Dataset/train/subject_train.txt",col.names=c("Subject"))
subjects_test <- read.table("UCI HAR Dataset/test/subject_test.txt",col.names=c("Subject"))
train$subject <- subjects_train$Subject
test$subject <- subjects_test$Subject

# Add a column to each which mentions which data set the data comes from
train$dataset <- "train"
test$dataset <- "test"

# Remove row names before row-binding
row.names(train) <- NULL
row.names(test) <- NULL
mergedData <- rbind(train,test)

# Add column names
colnames(mergedData) <- c(extractedFeatures,"activity","subject","dataset")

# Read the activity label descriptions from the activity_labels.txt file and convert the index
# to a numeric variable and the description to a character variable
activities <- read.table("UCI HAR Dataset/activity_labels.txt",col.names=c("activity","activity.description"))
activities$activity <- as.numeric(activities$activity)
activities$activity.description <- as.character(activities$activity.description)

# Replace the numeric activity labels to the descriptive versions
for (i in 1:nrow(activities)) {
  mergedData$activity[mergedData$activity == activities$activity[i]] <- activities$activity.description[i]
}

# Convert the activities and dataset variables to factor variables for efficient storage
mergedData$activity <- as.factor(mergedData$activity)
mergedData$subject <- as.factor(mergedData$subject)
mergedData$dataset <- as.factor(mergedData$dataset)

# Create a tidy dataset with the average of each variable for each activity and each subject
library(plyr)
tidydata <- ddply(mergedData, .(subject,activity), numcolwise(mean))
head(tidydata[,1:5],n=12)

# Save this data frame as a csv-file
write.csv(file="tidydata.csv",x=tidydata)